[build]
  # Set the build command
  command = "npm run build"

  # Set the publish directory (where the build output is located)
  publish = "nodejs-passport-postgresql" # Change 'dist' to the actual directory where your build output is

[context.production]
  command = "npm run build"
  publish = "nodejs-passport-postgresql" # Change 'dist' to the actual directory where your build output is

[context.deploy-preview]
  command = "npm run build"
  publish = "nodejs-passport-postgresql" # Change 'dist' to the actual directory where your build output is

[context.branch-deploy]
  command = "npm run build"
  publish = "nodejs-passport-postgresql" # Change 'dist' to the actual directory where your build output is

# Additional settings can be added as needed
